language: node_js
node_js:
  - "8.2.1"

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/C:/Users/mpetk/AppData/Roaming/npm --version

script:
  - node_modules/.bin/newman run AllScripts_PoC.postman_collection(10).json --folder Tests -e tests/tests.postman_environment.jso